# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
    ]
